version: '3.7'

services:
  nginx:
    build: ./docker/nginx
    volumes: 
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - python

  mariadb:
    build: ./docker/mariadb/
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret

  phpmyadmin:
    build: ./docker/phpmyadmin/
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=default
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    links:
      - mariadb
    depends_on:
      - mariadb
  
  python:
    build: ./docker/python/
    # 8001portを開いてNginxとリンク、appプロジェクト、変更を検知してファイルをリロード、ログの出力設定
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/uwsgi.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - mariadb

volumes:
  dbvolume:
    driver: local