version: '3.7'

services:
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes: 
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - python

  mariadb:
    build: ./docker/mariadb/
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    build: ./docker/phpmyadmin/
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 8080:80
    links:
      - mariadb
    depends_on:
      - mariadb
  
  python:
    build: 
      context: .
      dockerfile: ./docker/python/Dockerfile
    # 8001portを開いてNginxとリンク、projectプロジェクト、変更を検知してファイルをリロード、ログの出力設定
    command: uwsgi --socket :8001 --module project.wsgi --py-autoreload 1 --logto /tmp/uwsgi.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - mariadb

volumes:
  dbvolume:
    driver: local